version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.5.1
        environment:
          CI: true
    working_directory: /home/circleci/formulator
    steps:
      - checkout
      - run: bin/setup
      - run: MIX_ENV=prod mix compile --warnings-as-errors
      - run: bin/test_suite
