version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.6
        environment:
          MIX_ENV: test
    working_directory: ~/app
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          keys:
            - v2-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v2-mix-cache-{{ .Branch }}
            - v2-mix-cache
      - restore_cache:
          keys:
            - v2-build-cache-{{ .Branch }}-{{ checksum ".tool-versions" }}
            - v2-build-cache-{{ .Branch }}
            - v2-build-cache
      - run: mix do deps.get, compile --warnings-as-errors
      - save_cache:
          key: v2-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v2-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v2-mix-cache
          paths: "deps"
      - save_cache:
          key: v2-build-cache-{{ .Branch }}-{{ checksum ".tool-versions" }}
          paths: "_build"
      - save_cache:
          key: v2-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v2-build-cache
          paths: "_build"
      - run: mix test

experimental:
  notify:
    branches:
      only:
        - master
